// prefix font Family
const DEFAULT_PREFIX_FONT_FAMILY = 'Roboto'

// fontFamily
export const FONT_FAMILY = {
  BLACK: `${DEFAULT_PREFIX_FONT_FAMILY}-Black`,
  BLACK_ITALIC: `${DEFAULT_PREFIX_FONT_FAMILY}-BlackItalic`,
  ITALIC: `${DEFAULT_PREFIX_FONT_FAMILY}-Italic`,
  REGULAR: `${DEFAULT_PREFIX_FONT_FAMILY}-Regular`,
  BOLD: `${DEFAULT_PREFIX_FONT_FAMILY}-Bold`,
  BOLD_ITALIC: `${DEFAULT_PREFIX_FONT_FAMILY}-BoldItalic`,
  LIGHT: `${DEFAULT_PREFIX_FONT_FAMILY}-Light`,
  LIGHT_ITALIC: `${DEFAULT_PREFIX_FONT_FAMILY}-LightItalic`,
  MEDIUM: `${DEFAULT_PREFIX_FONT_FAMILY}-Medium`,
  MEDIUM_ITALIC: `${DEFAULT_PREFIX_FONT_FAMILY}-MediumItalic`,
  THIN: `${DEFAULT_PREFIX_FONT_FAMILY}-Thin`,
  THIN_ITALIC: `${DEFAULT_PREFIX_FONT_FAMILY}-ThinItalic`,
}

export default {
  FONT_FAMILY,
}
